from __future__ import annotations

# Try absolute imports first, fall back to relative
try:
    from etl.lib.validators import run_validators, _apply_jsonl_validators, _apply_json_validators, _read_jsonl
    # Re-export all validator functions for backward compatibility
    from etl.lib.validators import (
    _validate_field_presence,
    _validate_unique,
    _validate_composite_unique,
    _validate_parent_exists,
    _validate_crossref_jsonl,
    _validate_crossref_json,
    _validate_transform_ids_in,
    _validate_transform_ids_in_objects,
    _validate_path_transform_ids_in,
    _validate_no_duplicates,
    _validate_hierarchy_consistency,
    _validate_parameter_consistency,
    _validate_schema_enum_compliance,
    _validate_id_format_consistency,
    _validate_required_fields_present,
    _validate_cross_references_exist,
    _validate_hierarchy_acyclic,
    _validate_expected_parents,
    _validate_parameter_types_consistent,
    _validate_no_duplicate_definitions,
    _validate_part_categories,
    _validate_part_category_values,
    _validate_part_naming_convention,
    _validate_part_hierarchy_integrity,
    _validate_array_of_objects,
    _validate_set_nonempty,
    _validate_json_pointer_equals,
    _validate_hierarchy_consistency_json,
    _validate_schema_enum_compliance_json,
    _validate_id_format_consistency_json,
    _validate_required_fields_present_json,
    _validate_cross_references_exist_json,
    _validate_hierarchy_acyclic_json,
    _validate_expected_parents_json,
    _validate_parameter_types_consistent_json,
    _validate_parameter_consistency_json,
    _validate_no_duplicate_definitions_json,
    _validate_no_duplicates_json,
    )
except ImportError:
    # Fall back to relative imports when running from etl directory
    from lib.validators import run_validators, _apply_jsonl_validators, _apply_json_validators, _read_jsonl
    # Re-export all validator functions for backward compatibility
    from lib.validators import (
    _validate_field_presence,
    _validate_unique,
    _validate_composite_unique,
    _validate_parent_exists,
    _validate_crossref_jsonl,
    _validate_crossref_json,
    _validate_transform_ids_in,
    _validate_transform_ids_in_objects,
    _validate_path_transform_ids_in,
    _validate_no_duplicates,
    _validate_hierarchy_consistency,
    _validate_parameter_consistency,
    _validate_schema_enum_compliance,
    _validate_id_format_consistency,
    _validate_required_fields_present,
    _validate_cross_references_exist,
    _validate_hierarchy_acyclic,
    _validate_expected_parents,
    _validate_parameter_types_consistent,
    _validate_no_duplicate_definitions,
    _validate_part_categories,
    _validate_part_category_values,
    _validate_part_naming_convention,
    _validate_part_hierarchy_integrity,
    _validate_array_of_objects,
    _validate_set_nonempty,
    _validate_json_pointer_equals,
    _validate_hierarchy_consistency_json,
    _validate_schema_enum_compliance_json,
    _validate_id_format_consistency_json,
    _validate_required_fields_present_json,
    _validate_cross_references_exist_json,
    _validate_hierarchy_acyclic_json,
    _validate_expected_parents_json,
    _validate_parameter_types_consistent_json,
    _validate_parameter_consistency_json,
    _validate_no_duplicate_definitions_json,
    _validate_no_duplicates_json,
    )